import type { ThemeId, ThemeDefinition } from "./types";

export const BUILTIN_THEMES: readonly ThemeDefinition[] = [
  {
    id: "aura",
    name: "Aura",
    source: "builtin",
    colors: {
      bg: "#15141b",
      border: "#3d375e",
      text: "#edecee",
      textDim: "#6d6d6d",
      accent: "#a277ff",
      success: "#61ffca",
      warning: "#ffca85",
      error: "#ff6767",
    },
  },
  {
    id: "carbon-fox",
    name: "Carbon Fox",
    source: "builtin",
    colors: {
      bg: "#161616",
      border: "#353535",
      text: "#f2f4f8",
      textDim: "#7b7c7e",
      accent: "#78a9ff",
      success: "#42be65",
      warning: "#ff832b",
      error: "#ee5396",
    },
  },
  {
    id: "catppuccin-frappe",
    name: "Catppuccin Frappe",
    source: "builtin",
    colors: {
      bg: "#303446",
      border: "#51576d",
      text: "#c6d0f5",
      textDim: "#a5adce",
      accent: "#8caaee",
      success: "#a6d189",
      warning: "#e5c890",
      error: "#e78284",
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    source: "builtin",
    colors: {
      bg: "#eff1f5",
      border: "#bcc0cc",
      text: "#4c4f69",
      textDim: "#8c8fa1",
      accent: "#1e66f5",
      success: "#40a02b",
      warning: "#df8e1d",
      error: "#d20f39",
    },
  },
  {
    id: "catppuccin-macchiato",
    name: "Catppuccin Macchiato",
    source: "builtin",
    colors: {
      bg: "#24273a",
      border: "#494d64",
      text: "#cad3f5",
      textDim: "#a5adcb",
      accent: "#8aadf4",
      success: "#a6da95",
      warning: "#eed49f",
      error: "#ed8796",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    source: "builtin",
    colors: {
      bg: "#1e1e2e",
      border: "#45475a",
      text: "#cdd6f4",
      textDim: "#a6adc8",
      accent: "#89b4fa",
      success: "#a6e3a1",
      warning: "#f9e2af",
      error: "#f38ba8",
    },
  },
  {
    id: "cobalt",
    name: "Cobalt",
    source: "builtin",
    colors: {
      bg: "#002240",
      border: "#1a3a5c",
      text: "#ffffff",
      textDim: "#6688aa",
      accent: "#0088ff",
      success: "#3ad900",
      warning: "#ffc600",
      error: "#ff0000",
    },
  },
  {
    id: "curse",
    name: "Curse",
    source: "builtin",
    colors: {
      bg: "#0a0a0f",
      border: "#2a2a3a",
      text: "#c0c0d0",
      textDim: "#606070",
      accent: "#8a2be2",
      success: "#00ff7f",
      warning: "#ffa500",
      error: "#dc143c",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    source: "builtin",
    colors: {
      bg: "#282a36",
      border: "#44475a",
      text: "#f8f8f2",
      textDim: "#6272a4",
      accent: "#bd93f9",
      success: "#50fa7b",
      warning: "#f1fa8c",
      error: "#ff5555",
    },
  },
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    source: "builtin",
    colors: {
      bg: "#2d353b",
      border: "#475258",
      text: "#d3c6aa",
      textDim: "#859289",
      accent: "#7fbbb3",
      success: "#a7c080",
      warning: "#dbbc7f",
      error: "#e67e80",
    },
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    source: "builtin",
    colors: {
      bg: "#fdf6e3",
      border: "#d5c4a1",
      text: "#5c6a72",
      textDim: "#939f91",
      accent: "#3a94c5",
      success: "#8da101",
      warning: "#dfa000",
      error: "#f85552",
    },
  },
  {
    id: "flexoki-dark",
    name: "Flexoki Dark",
    source: "builtin",
    colors: {
      bg: "#100f0f",
      border: "#343331",
      text: "#cecdc3",
      textDim: "#878580",
      accent: "#4385be",
      success: "#879a39",
      warning: "#d0a215",
      error: "#af3029",
    },
  },
  {
    id: "flexoki-light",
    name: "Flexoki Light",
    source: "builtin",
    colors: {
      bg: "#fffcf0",
      border: "#e6e4d9",
      text: "#100f0f",
      textDim: "#6f6e69",
      accent: "#205ea6",
      success: "#66800b",
      warning: "#ad8301",
      error: "#af3029",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    source: "builtin",
    colors: {
      bg: "#0d1117",
      border: "#30363d",
      text: "#c9d1d9",
      textDim: "#8b949e",
      accent: "#58a6ff",
      success: "#3fb950",
      warning: "#d29922",
      error: "#f85149",
    },
  },
  {
    id: "github-light",
    name: "GitHub Light",
    source: "builtin",
    colors: {
      bg: "#ffffff",
      border: "#d0d7de",
      text: "#24292f",
      textDim: "#57606a",
      accent: "#0969da",
      success: "#1a7f37",
      warning: "#9a6700",
      error: "#cf222e",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    source: "builtin",
    colors: {
      bg: "#282828",
      border: "#504945",
      text: "#ebdbb2",
      textDim: "#928374",
      accent: "#83a598",
      success: "#b8bb26",
      warning: "#fabd2f",
      error: "#fb4934",
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    source: "builtin",
    colors: {
      bg: "#fbf1c7",
      border: "#d5c4a1",
      text: "#3c3836",
      textDim: "#7c6f64",
      accent: "#076678",
      success: "#79740e",
      warning: "#b57614",
      error: "#9d0006",
    },
  },
  {
    id: "iu",
    name: "IU",
    source: "builtin",
    colors: {
      bg: "#1c1c28",
      border: "#3e3e5c",
      text: "#e0e0f0",
      textDim: "#8888aa",
      accent: "#ff9ecd",
      success: "#86e1a0",
      warning: "#f5d76e",
      error: "#ff7b7b",
    },
  },
  {
    id: "kanagawa",
    name: "Kanagawa",
    source: "builtin",
    colors: {
      bg: "#1f1f28",
      border: "#363646",
      text: "#dcd7ba",
      textDim: "#727169",
      accent: "#7e9cd8",
      success: "#98bb6c",
      warning: "#e6c384",
      error: "#c34043",
    },
  },
  {
    id: "lucent-orng",
    name: "Lucent Orange",
    source: "builtin",
    colors: {
      bg: "#1a1410",
      border: "#3a2a20",
      text: "#f0e0d0",
      textDim: "#8a7a6a",
      accent: "#ff8c42",
      success: "#7fba4a",
      warning: "#ffcc00",
      error: "#ff4444",
    },
  },
  {
    id: "material",
    name: "Material",
    source: "builtin",
    colors: {
      bg: "#263238",
      border: "#37474f",
      text: "#eeffff",
      textDim: "#546e7a",
      accent: "#82aaff",
      success: "#c3e88d",
      warning: "#ffcb6b",
      error: "#f07178",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    source: "builtin",
    colors: {
      bg: "#0d0208",
      border: "#003b00",
      text: "#00ff41",
      textDim: "#008f11",
      accent: "#00ff41",
      success: "#00ff41",
      warning: "#ccff00",
      error: "#ff0000",
    },
  },
  {
    id: "mercury",
    name: "Mercury",
    source: "builtin",
    colors: {
      bg: "#1e2127",
      border: "#3b4048",
      text: "#d7dae0",
      textDim: "#7f848e",
      accent: "#c0caf5",
      success: "#9ece6a",
      warning: "#e0af68",
      error: "#f7768e",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    source: "builtin",
    colors: {
      bg: "#272822",
      border: "#49483e",
      text: "#f8f8f2",
      textDim: "#75715e",
      accent: "#66d9ef",
      success: "#a6e22e",
      warning: "#e6db74",
      error: "#f92672",
    },
  },
  {
    id: "night-owl",
    name: "Night Owl",
    source: "builtin",
    colors: {
      bg: "#011627",
      border: "#122d42",
      text: "#d6deeb",
      textDim: "#637777",
      accent: "#82aaff",
      success: "#22da6e",
      warning: "#ecc48d",
      error: "#ef5350",
    },
  },
  {
    id: "nord",
    name: "Nord",
    source: "builtin",
    colors: {
      bg: "#2e3440",
      border: "#4c566a",
      text: "#eceff4",
      textDim: "#d8dee9",
      accent: "#88c0d0",
      success: "#a3be8c",
      warning: "#ebcb8b",
      error: "#bf616a",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    source: "builtin",
    colors: {
      bg: "#282c34",
      border: "#3e4451",
      text: "#abb2bf",
      textDim: "#5c6370",
      accent: "#61afef",
      success: "#98c379",
      warning: "#e5c07b",
      error: "#e06c75",
    },
  },
  {
    id: "orng",
    name: "ORNG",
    source: "builtin",
    colors: {
      bg: "#0f0f0f",
      border: "#2a2a2a",
      text: "#f0f0f0",
      textDim: "#666666",
      accent: "#ff6600",
      success: "#44cc44",
      warning: "#ffaa00",
      error: "#ff3333",
    },
  },
  {
    id: "osaka-jade",
    name: "Osaka Jade",
    source: "builtin",
    colors: {
      bg: "#0c1810",
      border: "#1e3a28",
      text: "#c8e0d0",
      textDim: "#6a8878",
      accent: "#50b080",
      success: "#68d098",
      warning: "#c8a858",
      error: "#c85050",
    },
  },
  {
    id: "pale-night",
    name: "Palenight",
    source: "builtin",
    colors: {
      bg: "#292d3e",
      border: "#444267",
      text: "#a6accd",
      textDim: "#676e95",
      accent: "#82aaff",
      success: "#c3e88d",
      warning: "#ffcb6b",
      error: "#f07178",
    },
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    source: "builtin",
    colors: {
      bg: "#191724",
      border: "#26233a",
      text: "#e0def4",
      textDim: "#908caa",
      accent: "#c4a7e7",
      success: "#9ccfd8",
      warning: "#f6c177",
      error: "#eb6f92",
    },
  },
  {
    id: "solarized",
    name: "Solarized Dark",
    source: "builtin",
    colors: {
      bg: "#002b36",
      border: "#073642",
      text: "#839496",
      textDim: "#586e75",
      accent: "#268bd2",
      success: "#859900",
      warning: "#b58900",
      error: "#dc322f",
    },
  },
  {
    id: "synthwave-84",
    name: "Synthwave 84",
    source: "builtin",
    colors: {
      bg: "#262335",
      border: "#3b3a4a",
      text: "#f0eff1",
      textDim: "#848bbd",
      accent: "#ff7edb",
      success: "#72f1b8",
      warning: "#fede5d",
      error: "#fe4450",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    source: "builtin",
    colors: {
      bg: "#1a1b26",
      border: "#33467c",
      text: "#a9b1d6",
      textDim: "#565f89",
      accent: "#7aa2f7",
      success: "#9ece6a",
      warning: "#e0af68",
      error: "#f7768e",
    },
  },
  {
    id: "versailles",
    name: "Versailles",
    source: "builtin",
    colors: {
      bg: "#f5f0e8",
      border: "#d0c8b8",
      text: "#3a3530",
      textDim: "#7a756a",
      accent: "#8b7355",
      success: "#5a7a50",
      warning: "#b08050",
      error: "#a04040",
    },
  },
  {
    id: "vesper",
    name: "Vesper",
    source: "builtin",
    colors: {
      bg: "#101010",
      border: "#282828",
      text: "#b0b0b0",
      textDim: "#606060",
      accent: "#ffc799",
      success: "#99ffc7",
      warning: "#ffe099",
      error: "#ff9999",
    },
  },
  {
    id: "zenburn",
    name: "Zenburn",
    source: "builtin",
    colors: {
      bg: "#3f3f3f",
      border: "#5f5f5f",
      text: "#dcdccc",
      textDim: "#7f9f7f",
      accent: "#8cd0d3",
      success: "#7f9f7f",
      warning: "#f0dfaf",
      error: "#cc9393",
    },
  },
];

const THEME_ORDER: ThemeId[] = [
  "terminal",
  ...BUILTIN_THEMES.map((t) => t.id).sort(),
];

export function listThemeIds(): ThemeId[] {
  return THEME_ORDER;
}

export function getThemeName(id: ThemeId): string {
  if (id === "terminal") return "Terminal";
  const theme = BUILTIN_THEMES.find((t) => t.id === id);
  return theme?.name ?? id;
}

export function getBuiltinTheme(id: ThemeId): ThemeDefinition | undefined {
  return BUILTIN_THEMES.find((t) => t.id === id);
}
